version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5172:5172"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ticketingdb;Username=postgres;Password=postgres
      - ConnectionStrings__RedisConnection=redis:6379
      - ASPNETCORE_URLS=http://+:5172
      - SEED_ADMIN_USERID=N3BqsC_MuvOJCdIrU2lZ13rdLoTBKs4YqxkxtMuJXbY
      - SEED_IN_DOCKER=true
      - SEED_ADMIN_EMAIL=adi.cizmic@emediapatch.com
      - SEED_ADMIN_FIRSTNAME=Adi
      - SEED_ADMIN_LASTNAME=Cizmic
    depends_on:
      - postgres
      - redis
      

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketingdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
